### ISSUE TITLE
warning in doc/examples/ex44

### ISSUE THREAD

**Issue by yoe** [PhilipHazel/pmw#2]
I'm about to upload PMW 5.20 to Debian.

As part of that, I rebuild the spec.pdf file from source, as required by Debian policies.

This produces a warning:

```
PMW version 5.20
** Warning: [stavelines <n>] is deprecated; use [stave m/<n>] instead
   Detected near line 6 of examples/ex44
[stave 1 hclef 0 stavelines 1]
----------------------------->
```

This doesn't look like a critical problem, but it might be a good idea if the documentation's examples match the preferred input?

**Comment by PhilipHazel** [comment]
Oh dear. Looks like I didn't rebuild the examples for the last update. I have now corrected the issue and committed the updated file and rebuilt the doc. Thanks for noticing and for looking after PMW for Debian.
