### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by prlw1** [PhilipHazel/pmw#5]
I grabbed PMW-5.22 and compiled with
```
PMW configuration summary:

    C compiler .......................: gcc
    C compiler flags .................: -O2 -g -O0
    Linker flags .....................: 
    Install pmw command in ...........: /usr/pkg/bin
    Install shared data in ...........: /usr/pkg/share/pmw
    Install man page in ..............: /usr/pkg/man
    Support .pmwrc file ..............: yes
    Support B2PF text processing .....: no
    Support for MusicXML input .......: no
```
took the example from `5. Getting started with PMW encoding'
```
heading "|Happy Birthday"
breakbarlines
underlaysize 9.5
notespacing *1.1
key F
time 3/4
unfinished

[stave 1 treble 1 text underlay]
"Hap-py birth-day to you, hap-py birth-day to you. Hap-py"
[nocheck] [nocount] c-.; c= |
dcf | E c-.; c= | dcg | F c-.; c= |
[endstave]

[stave 2 bass 0]
[nocheck] r | F. | C. | c d e | F. |
[endstave]
```
and see
```
$ pmw bday
[1]   Segmentation fault (core dumped) pmw bday
```
Story so far:
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000000394cc in pmw_read () at pmw_read.c:1196
1196          read_nextsigc();
(gdb) bt
#0  0x00000000000394cc in pmw_read () at pmw_read.c:1196
#1  0x000000000005489a in read_file (ft=FT_AUTO) at read.c:435
#2  0x0000000000020000 in main (argc=2, argv=0x7f7fffffe6c8) at main.c:1127
(gdb) list
1191          pmw_reading_stave = TRUE;
1192          pmw_read_stave();
1193          pmw_reading_stave = FALSE;
1194          barlinestyles[srs.stavenumber] = srs.barlinestyle;
1195          if (read_c == ENDFILE) break;
1196          read_nextsigc();
1197          if (Ustrncmpic(main_readbuffer + read_i - 1, "[stave ", 7) != 0 &&
1198              Ustrncmpic(main_readbuffer + read_i - 1, "[staff ", 7) != 0) break;
1199          }
1200        }
(gdb) print read_c
$1 = 4294967295
(gdb) whatis read_c
type = uint32_t
```
(edited - the backtrace without -O0 made no sense)

`4294967295=FFFFFFFF`

`src/pmw.h:#define ENDFILE            0xffffffffu       /* Too large to be a character */`

so shouldn't have reached 1196?

**Comment by prlw1** [comment]
The fun of debugging macros - read_nextsigc is a macro.
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000042720a in pmw_read () at pmw_read.c:1199
1199          while (isspace(read_c))
(gdb) list
1194          barlinestyles[srs.stavenumber] = srs.barlinestyle;
1195    printf("%u %u %u\n", read_c, ENDFILE, read_c == ENDFILE);
1196          if (read_c == ENDFILE) break;
1197          /* read_nextsigc(); */
1198          read_nextc();
1199          while (isspace(read_c))
1200              read_nextc();
1201          if (Ustrncmpic(main_readbuffer + read_i - 1, "[stave ", 7) != 0 &&
1202              Ustrncmpic(main_readbuffer + read_i - 1, "[staff ", 7) != 0) break;
1203          }
(gdb) print read_c
$1 = 4294967295
```
so max uint32 is going to isspace(signed int), and I can reproduce the segmentation fault with
```
#include <ctype.h>
#include <stdio.h>

int main()
{
        printf("%d", isspace(0xffffffffu));

        return 0;
}
```

**Comment by PhilipHazel** [comment]
Needless to day, when I run exactly the same file, it works no problem.  I wonder what the difference is? I've only just got back from being away, but I will look further when I get a moment....

**Comment by prlw1** [comment]
Thanks for trying to reproduce! That gives a clue:

I just tried the short comment 2 `isspace(0xffffffffu)` code on ubuntu 20.04.1 and didn't get a segmentation fault, butI do on NetBSD.

A cursory glance at pmw_read() suggests end-of-file is tested for, and thereafter several characters are read during which end-of-file is reached but is not tested for.

**Comment by PhilipHazel** [comment]
What hardware and OS are you using?  Maybe it doesn't matter. I think I can see a logic error in the code in that it would crash if it encountered ENDFILE while skipping white space. However, looking through other code that precedes this, I cannot see an obvious way of provoking it. I will keep looking - probably tomorrow now. Meanwhile I tried the isspace() test on my Arch Linux box and it printed "0". So this is some kind of OS-dependent thing. This is very old code; it's been around for over a decade. Why hasn't this happened before? Thanks for the report, btw. Nice to know people are looking at PMW. FYI I am in the very, very early stages of upgrading it to write PDF output directly as an alternative to PostScript. But that will be months away. Oh, one final point, can you check your input file to see exactly what characters follow the final [endstave]?

**Comment by spaskalev** [comment]
Testing pwm with a fuzzing tool like AFL/AFL++ may reveal other crashes like it.

**Comment by prlw1** [comment]
The difference in behaviour is explained under the "CAVEATS" section of [ctype(3)](https://man.netbsd.org/ctype.3)

**Comment by prlw1** [comment]
P.S. I then successfully typeset the bit of BWV 140 I needed using pmw 4.51.

**Comment by PhilipHazel** [comment]
But both ctype(3) and the C11 standard say that the value EOF is acceptable. What is EOF in BSD? On LInux it's -1 which is of course 0xffffffff. Anyway, I am now going to chase this up some more. Glad you managed to get a version of PMW that worked for you.

**Comment by prlw1** [comment]
> -1 which is of course 0xffffffff

Amusingly, apparently not so:

```
#include <ctype.h>
#include <stdio.h>

int main()
{
        printf("%d  0x%x\n", EOF, EOF);
        printf("%d\n", isspace(EOF));
        printf("%d\n", isspace(-1));
        printf("%d\n", isspace((int)0xffffffff));
        /* printf("%d\n", isspace(0xffffffff)); XXX segmentation fault */

        return 0;
}
```
output
```
-1  0xffffffff
0
0
0
`
The signedness matters...

**Comment by PhilipHazel** [comment]
Yes, I had just come to the same conclusion. Sigh. The whole reason I used unsigned variables in PMW was that I had been caught out too many times because some systems make char signed and some don't. That was back in the late 1980's when I was first developing PMW and using char variables (before UTF support and the move to 32-bit characters). The solution here, I guess, is to put a cast in calls to isspace() and other ctype function calls. I will do a trawl through all the source. I suspect that might be easier than changing to using signed int variables. 

Incidentally (1) the failing code is identical in 5.21 and 5.22, so why one worked and the other didn't is odd. (2) While looking at this I found a completely unrelated bug, which I will also fix.

**Comment by prlw1** [comment]
I used version 4.51 instead (not 5.21) - this was the first time I tried a github version, i.e., first time on the 5 series. (I could have switched on the RiscPC too and used PMS ;-) )

**Comment by PhilipHazel** [comment]
It turns out that simply changing read_c to be signed rather than unsigned doesn't cause any other issues, and should solve the problem. I'd forgotten how it all worked, but I now see that most of the time the code is dealing with unsigned chars, which work fine with isspace() etc, because they can always be promoted to a positive integer value. I have made this patch and pushed the source to HEAD. I would be grateful if you could test and let me know if it does indeed fix your problem.

**Comment by PhilipHazel** [comment]
Excellent. I will close this issue.
