### ISSUE TITLE
Crashes discovered by AFL++

### ISSUE THREAD

**Issue by spaskalev** [PhilipHazel/pmw#6]
Based on the crash in #5 I decided to compile pmw under AFL++ and give it go. It has been running for a little over a few minutes but it already found a few inputs that would cause pmw to crash.

Those are not necessarily valid input in any way - the fuzzer will mutate them to test all paths in the program and try to get it to crash.

I will attach some of the inputs here.

**Comment by spaskalev** [comment]
I can't seem to upload binary files to github issues so I've posted the inputs at https://file.io/YmAqAA4hWAbl

**Comment by spaskalev** [comment]
After running the fuzzer for 45 minutes here's a the detected crashes. Most of them are segfaults and one is an endless loop - https://filebin.net/eyyyts8pial2zodj

**Comment by spaskalev** [comment]
Thank you for looking into it, so quickly at that! I'll sync to HEAD and run another session tonight.

**Comment by spaskalev** [comment]
I ran the fuzzer again for an hour after syncing to HEAD and recompiling pmw - it detected another set of crashes and hangs. I've uploaded the results at https://file.io/j7xbwjqbKEtq

**Comment by PhilipHazel** [comment]
I will look at some of those sometime in the next few days, but I am not going to look at all 288 files individually!

**Comment by spaskalev** [comment]
I agree, fuzzing can seem to produce a lot of stuff. Just to put it in context - the fuzzer ran over two and a half million executions of pmw in this session - having 288 bad inputs (almost certainly of similar failure types)  is like a drop in the ocean.

Hardening pmw against those inputs will allow it to be hosted for online use with less of a risk, which is something I've been looking at for a while. If you implement the direct PDF output that would be even greater as then ghostscript will no longer be required to distill the PostScript to PDF. And pmw is small enough that it could easily be compiled to web assembly and run directly in a modern browser.

I'll take a look at some of those input too and try to come up with patches.

Cheers!

**Comment by PhilipHazel** [comment]
I created some infrastructure to make it faster to scan those files for bugs. I have mended a number of bugs and believe that I have fixed everything those inputs threw up. All committed to HEAD.

**Comment by spaskalev** [comment]
Great work, after running the fuzzers for more than an hour they no longer detect any crashes!

**Comment by PhilipHazel** [comment]
Good. Back to the PDF work then for me.
